version: '3.1'
services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: ./frontend/Dockerfile.prod
    ports:
      - 4444:80
    networks:
      - taw_default
    restart: unless-stopped

  backend:
    build:
      context: ./backend/
      dockerfile: ../backend/Dockerfile
    networks:
      - taw_default
    restart: unless-stopped
  
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USR}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PSW}
    networks:
      - taw_default
    restart: always

networks:
  taw_default:
    driver: bridge
    name: taw_default
