version: '3.8'
services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile.prod
    container_name: taw-frontend
    ports:
      - 14200:80
    networks:
      - taw_default
    restart: unless-stopped

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile.prod
    container_name: taw-backend
    ports:
      - 3000:3000
    networks:
      - taw_default
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: taw-mongo
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USR}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PSW}
    volumes:
      - mongodata:/data/db
    networks:
      - taw_default
    ports:
      - 27018:27017 # enabled for debug purposes
    restart: unless-stopped

volumes:
  mongodata:

networks:
  taw_default:
    driver: bridge
    name: taw_default
