FROM node:20-alpine

ENV NODE_ENV=production

WORKDIR /app

COPY ./package.json .

RUN npm install

COPY ./dist .

RUN npm install -g pino-pretty

EXPOSE 3000

CMD [ "sh", "-c", "node ./api.js | pino-pretty"]

