version: '3.8'
services:
  mongo:
    image: mongo:6
    environment:
      # MONGO_INITDB_DATABASE: ${MONGO_DB}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USR}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PSW}
    volumes:
      - mongodata:/data/db
    networks:
      - taw_default
    ports:
      - 27018:27017
    restart: unless-stopped

volumes:
  mongodata:
    name: taw-project_mongodata
    external: true

networks:
  taw_default:
    name: taw_default
    # external: true

